### ISSUE TITLE
CTD - server when placing chests or spawn eggs

### ISSUE THREAD

**Issue by AngleWyrm** [AngleWyrm/Colonies#89]
from pmardle at http://mcmresurrection.enjin.com/forum/m/9402108/viewthread/5661606-open-0010-critical-crash/post/31922116#p31922116

Time: 1/26/13 7:39 PM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
at colonies.thephpdev.src.BlockMine.addBlockToTown(BlockMine.java:83)
at colonies.vector67.src.BlockColoniesChest.a(BlockColoniesChest.java:129)
at vl.placeBlockAt(ItemBlock.java:203)
at vl.a(ItemBlock.java:92)
at um.a(SourceFile:88)
at ir.a(ItemInWorldManager.java:413)
at iv.a(NetServerHandler.java:525)
at fl.a(SourceFile:58)
at cg.b(TcpConnection.java:451)
at iv.d(NetServerHandler.java:82)
at iw.b(NetworkListenThread.java:55)
at ht.b(SourceFile:30)
at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:704)
at ho.r(DedicatedServer.java:252)
at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:600)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:499)
at fy.run(SourceFile:856)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:141)
at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
... 17 more
Caused by: java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid side SERVER
at cpw.mods.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:38)
at cpw.mods.fml.relauncher.RelaunchClassLoader.runTransformers(RelaunchClassLoader.java:178)
at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:133)
... 19 more

A detailed walkthrough of the error, its code path and all known details is as follows:
-- System Details --
Details:
Minecraft Version: 1.4.5
Operating System: FreeBSD (amd64) version 8.3-RELEASE-p4
Java Version: 1.7.0_04, Oracle Corporation
Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 94144304 bytes (89 MB) / 192929792 bytes (183 MB) up to 1060372480 bytes (1011 MB)
JVM Flags: 8 total; -Xmn128M -Xms160M -Xmx1024M -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:ParallelGCThreads=2 -XX:+AggressiveOpts
AABB Pool Size: 3989 (223384 bytes; 0 MB) allocated, 3705 (207480 bytes; 0 MB) used
Suspicious classes: FML and Forge are installed
IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 63
FML: MCP v7.23 FML v4.5.21.486 Minecraft Forge 6.4.1.436 4 mods loaded, 4 mods active
mcp [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
FML [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
Forge [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
Colonies [Colonies](colonies-25-Jan-2013c_1359214290.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
Profiler Position: N/A (disabled)
Vec3 Pool Size: 1574 (88144 bytes; 0 MB) allocated, 1390 (77840 bytes; 0 MB) used
Player Count: 1 / 10; [iq]
Is Modded: Definitely; Server brand changed to 'forge,fml'
Type: Dedicated Server (map_server.txt)

**Comment by AngleWyrm** [comment]
RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid side SERVER
repeated in new crash report:

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2/2/13 10:43 AM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: colonies.anglewyrm.src.Utility.chatMessage(Ljava/lang/String;)V
at colonies.anglewyrm.src.BlockTownHall.a(BlockTownHall.java:53)
at vl.placeBlockAt(ItemBlock.java:203)
at vl.a(ItemBlock.java:92)
at um.a(SourceFile:88)
at ir.a(ItemInWorldManager.java:413)
at iv.a(NetServerHandler.java:525)
at fl.a(SourceFile:58)
at cg.b(TcpConnection.java:451)
at iv.d(NetServerHandler.java:82)
at iw.b(NetworkListenThread.java:55)
at ht.b(SourceFile:30)
at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:696)
at ho.r(DedicatedServer.java:252)
at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:592)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:499)
at fy.run(SourceFile:856)

A detailed walkthrough of the error, its code path and all known details is as follows:
-- System Details --
Details:
Minecraft Version: 1.4.5
Operating System: FreeBSD (amd64) version 8.3-RELEASE-p4
Java Version: 1.7.0_04, Oracle Corporation
Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 95644616 bytes (91 MB) / 193007616 bytes (184 MB) up to 1060372480 bytes (1011 MB)
JVM Flags: 8 total; -Xmn128M -Xms160M -Xmx1024M -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:ParallelGCThreads=2 -XX:+AggressiveOpts
AABB Pool Size: 2891 (161896 bytes; 0 MB) allocated, 1940 (108640 bytes; 0 MB) used
Suspicious classes: FML and Forge are installed
IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 63
FML: MCP v7.23 FML v4.5.2.459 Minecraft Forge 6.4.1.411 4 mods loaded, 4 mods active
mcp [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
FML [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
Forge [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
Colonies [Colonies](Colonies-1-Feb-2013_1359753414.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
Profiler Position: N/A (disabled)
Vec3 Pool Size: 2342 (131152 bytes; 0 MB) allocated, 2147 (120232 bytes; 0 MB) used
Player Count: 1 / 10; [iq]
Is Modded: Definitely; Server brand changed to 'forge,fml'
Type: Dedicated Server (map_server.txt)
