### ISSUE TITLE
CTD - when removing last house

### ISSUE THREAD

**Issue by AngleWyrm** [AngleWyrm/Colonies#91]
From IronTaxi at http://mcmresurrection.enjin.com/forum/m/9402108/viewthread/5760021-open-0011-high-crash-replicate

java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
at java.util.LinkedList.checkElementIndex(Unknown Source)
at java.util.LinkedList.remove(Unknown Source)
at colonies.anglewyrm.src.BlockHouse.removeChestFromTown(BlockHouse.java:71)
at colonies.src.BlockColoniesChest.a(BlockColoniesChest.java:273)
at zs.a(Chunk.java:706)
at zs.a(Chunk.java:648)
at xv.b(World.java:563)
at xv.e(World.java:672)
at amj.removeBlockByPlayer(Block.java:1494)
at ir.d(ItemInWorldManager.java:262)
at ir.b(ItemInWorldManager.java:295)
at ir.a(ItemInWorldManager.java:158)
at iv.a(NetServerHandler.java:445)
at ej.a(SourceFile:46)
at cf.b(MemoryConnection.java:79)
at iv.d(NetServerHandler.java:82)
at iw.b(NetworkListenThread.java:55)
at bdr.b(IntegratedServerListenThread.java:111)
at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:696)
at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:592)
at bdo.q(IntegratedServer.java:110)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:499)
at fy.run(SourceFile:856)inecraftServer.java:499)
at fy.run(SourceFile:856)

**Comment by AngleWyrm** [comment]
From jeremy at http://mcmresurrection.enjin.com/forum/page/1/m/9402108/viewthread/5834828-open-0012-high-crash#p32821580

---- Minecraft Crash Report ----
// I feel sad now :(

Time: 2/9/13 5:57 PM
Description: Ticking memory connection

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.LinkedList.checkElementIndex(Unknown Source)
at java.util.LinkedList.remove(Unknown Source)
at colonies.anglewyrm.src.BlockHouse.removeChestFromTown(BlockHouse.java:71)
at colonies.src.BlockColoniesChest.a(BlockColoniesChest.java:273)
at zs.a(Chunk.java:706)
at zs.a(Chunk.java:648)
at xv.b(World.java:563)
at xv.e(World.java:672)
at amj.removeBlockByPlayer(Block.java:1494)
at ir.d(ItemInWorldManager.java:262)
at ir.b(ItemInWorldManager.java:295)
at ir.a(ItemInWorldManager.java:158)
at iv.a(NetServerHandler.java:445)
at ej.a(SourceFile:46)
at cf.b(MemoryConnection.java:79)
at iv.d(NetServerHandler.java:82)
at iw.b(NetworkListenThread.java:55)
at bdr.b(IntegratedServerListenThread.java:111)
at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:696)
at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:592)
at bdo.q(IntegratedServer.java:110)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:499)
at fy.run(SourceFile:856)

A detailed walkthrough of the error, its code path and all known details is as follows:
-- System Details --
Details:
Minecraft Version: 1.4.5
Operating System: Windows 7 (x86) version 6.1
Java Version: 1.7.0_07, Oracle Corporation
Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
Memory: 232488480 bytes (221 MB) / 519110656 bytes (495 MB) up to 1037959168 bytes (989 MB)
JVM Flags: 2 total; -Xms512m -Xmx1024m
AABB Pool Size: 664 (37184 bytes; 0 MB) allocated, 540 (30240 bytes; 0 MB) used
Suspicious classes: FML and Forge are installed
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
FML: MCP v7.23 FML v4.5.2.459 Minecraft Forge 6.4.1.411 4 mods loaded, 4 mods active
mcp [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
FML [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
Forge [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
Colonies [Colonies](colonies-8-Feb-2013_1360397161.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available
Profiler Position: N/A (disabled)
Vec3 Pool Size: 112 (6272 bytes; 0 MB) allocated, 87 (4872 bytes; 0 MB) used
Player Count: 1 / 8; [iq]
Type: Integrated Server (map_client.txt)
Is Modded: Definitely; Client brand changed to 'forge,fml'

**Comment by Jerecools** [comment]
Its good that you see my crash report I will try to report another crash or maybe I can report a bug that I found. I will try that in Pre-Alpha Revision 13 when it is out. Now I found out what to write in the title in reporting crash and bugs.

**Comment by Jerecools** [comment]
Finally its fixed thanks for fixing it. I will keep finding bugs and crashes so keep adding new things to that mod because I know that there is always bugs in new things.
